sudo: required
services:
  - docker

before_install:
  - docker build -t shaheermir/address-book -f Dockerfile.dev .

script:
  - docker run -e CI=true shaheermir/address-book npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'address-book-ng'
  env: 'Addressbookng-env'
  bucket_name: 'elasticbeanstalk-us-west-2-970327409342'
  bucket_path: 'address-book-ng'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
