sudo: required
services:
  - docker

before_install:
  - docker build -t shaheermir/address-book -f Dockerfile.dev .

script:
  - docker run -e CI=true shaheermir/address-book npm run test -- --coverage
