version: '3.7'
services:
  address-book:
    container_name: address-book-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: address-book:dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
